{
 "title": "S.M.A.R.T disk monitoring for Prometheus Dashboard",
 "description": "Smartmon Texfile node_exporter Dashboard",
 "tags": [
  "prometheus",
  "node_exporter",
  "smartmon",
  "smart"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(smartmon_device_info,instance)"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values({instance=~\"$instance\"},disk)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Disk Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unhealthy Disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(smartmon_device_smart_healthy{instance=~\"$instance\"})-sum(smartmon_device_smart_healthy{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Errors All Devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum( smartmon_reallocate_nand_blk_cnt_raw_value ) +\nsum( smartmon_reallocated_sector_ct_raw_value ) +\nsum( smartmon_reallocated_event_count_raw_value ) +\nsum( smartmon_raw_read_error_rate_raw_value ) +\nsum( smartmon_current_pending_sector_raw_value ) +\nsum( smartmon_offline_uncorrectable_raw_value ) +\nsum( smartmon_udma_crc_error_count_raw_value ) +\nsum( smartmon_seek_error_rate_raw_value ) +\nsum( smartmon_spin_retry_count_raw_value ) +\nsum( smartmon_multi_zone_error_rate_raw_value )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "description": "Devices that are active",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(smartmon_device_active)" }
   ]
  },
  {
   "title": "Temperature_Graph",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(smartmon_temperature{ instance=~\"$instance\", disk=~\"$disk\" }) by (instance, disk) OR avg(smartmon_temperature_celsius_raw_value{ instance=~\"$instance\", disk=~\"$disk\" }) by (instance, disk)",
     "legendFormat": "{{instance}}{{disk}}"
    }
   ]
  },
  {
   "title": "Temperture_Gauge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "smartmon_temperature{ instance=~\"$instance\", disk=~\"$disk\" } OR smartmon_temperature_celsius_raw_value{ instance=~\"$instance\", disk=~\"$disk\" }",
     "legendFormat": "{{ disk }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "options": {
    "content": "<p></p>\n<p style=\"text-align: center;font-size: x-large;face:arial;\">__________ Wear and Tear __________</p>"
   }
  },
  {
   "title": "Power_On_Hours",
   "type": "gauge",
   "description": "yellow after 2 years\nred after 4 years",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "smartmon_power_on_hours{ disk=~\"$disk\", instance=~\"$instance\" } OR smartmon_power_on_hours_raw_value{ disk=~\"$disk\", instance=~\"$instance\" }",
     "legendFormat": " {{disk}}"
    }
   ]
  },
  {
   "title": "Power_Cycle_Count",
   "type": "gauge",
   "description": "Number of times disk was turned on",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "smartmon_power_cycles{ instance=~\"$instance\", disk=~\"$disk\"} OR smartmon_power_cycle_count_raw_value { instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "options": {
    "content": "<p></p>\n<p style=\"text-align: center;font-size: x-large;face:arial;\">__________ SSD Specific Values __________</p>"
   }
  },
  {
   "title": "Remaining_Lifetime",
   "type": "gauge",
   "description": "Estimated remaining lifetime.\nBased on amount of written data.\n(Very vague one flash chip can be witten 10 000 times)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "smartmon_percent_lifetime_remain_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Written Data (\"TBW\")",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_written_bytes{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "<p></p>\n<p style=\"text-align: center;font-size: x-large;face:arial;\">__________ HDD Specific Values __________</p>"
   }
  },
  {
   "title": "Spin_Up_Time",
   "type": "timeseries",
   "description": "Average time to spin up disk. (in ms)\nHigh values indicate problems with the motor.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "smartmon_spin_up_time_raw_value",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Power_Off_Retract_Count",
   "type": "gauge",
   "description": "Number of unexpected power outages (no correct shutdown) \nThis kind of shutdown lowers the lifetime of a disk way more than a clean shutdown",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "smartmon_power_off_retract_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Start_Stop_Count",
   "type": "gauge",
   "description": "Counts start/stop events.\nHigh values indicate high wear.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "smartmon_start_stop_count_raw_value { instance=~\"$instance\", disk=~\"$disk\" }",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Load_Cycle_Count",
   "type": "gauge",
   "description": "Number times the head was placed in the parking area.\nMostly mobile disks.\n300000 times is intended.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "smartmon_load_cycle_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Device_Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "smartmon_device_info" }
   ]
  },
  { "title": "General Disk Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "current_pending_sector",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "smartmon_current_pending_sector_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "offline_uncorrectable",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "smartmon_offline_uncorrectable_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reallocated_event_count",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "smartmon_reallocated_event_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reallocated_sector_count",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "smartmon_reallocated_sector_ct_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reallocate_nand_blk_count",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "smartmon_reallocate_nand_blk_cnt_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "raw_read_error_rate",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "smartmon_raw_read_error_rate_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "udma_crc_error_count",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "smartmon_udma_crc_error_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HDD Sepecific Disk Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "multi_zone_error_rate",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "smartmon_multi_zone_error_rate_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "seek_error_rate",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "smartmon_seek_error_rate_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spin_retry_count",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "smartmon_spin_retry_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}